# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Fire It App Blog
tagline:             'things to rememeber to get fired up in the future'
description:         'Things to rememeber to get fired up in the future. Theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:
baseurl:             'http://tavikukko.github.io'
paginate:            5

# About/contact
author:
  name:              Tomi Tavela
  url:               https://twitter.com/tavikukko
  email:

# Custom vars
version:             1.0.0
